# casks (apps)
cask 'font-commit-mono'
cask 'font-symbols-only-nerd-font'
cask 'ghostty@tip'
cask 'rancher'
cask 'windows-app'
cask 'zen'

# formulas n stuff
brew 'git'
brew 'keychain'
brew 'zsh'
brew 'oh-my-posh'
brew 'zsh-vi-mode'
brew 'zsh-autosuggestions'
brew 'neovim'
brew 'lazygit'
brew 'k9s'
brew 'cheat'
brew 'make'
brew 'plantuml'
brew 'go@1.24'
brew 'eza'
